apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minnow-nodejs-stage
  namespace: rhtap-test-organization-jk
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/minnow-nodejs/overlays/stage
    repoURL: https://github.com/rhtap-test-organization-jk/minnow-nodejs-gitops.git
    targetRevision: main
  destination:
    namespace: rhtap-test-organization-jk-stage
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: rhtap-test-organization-jk
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true

