apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: minnow-nodejs 
  janus-idp.io/tekton: minnow-nodejs
  backstage.io/kubernetes-id: minnow-nodejs
  backstage.io/kubernetes-namespace: rhtap-test-organization-jk 
  app.kubernetes.io/part-of: minnow-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  